# This grammer document describes how to parse command line arguments.
# This document attempts to adhere to GNU getopt_long semantics, which is an extension
# of POSIX getopt behavior, and allows mixing the order of positionals and options.
# Ref: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
# Ref: https://sourceware.org/glibc/manual/latest/html_node/Argument-Syntax.html
#
# The style of this document should align with zig-spec grammer document.
# Ref: https://codeberg.org/ziglang/zig-spec/src/branch/master/grammar/grammar.peg#
# Ref: https://en.wikipedia.org/wiki/Parsing_expression_grammar

# Examples are all in ZON format.


# ArgV: the operating system provided argument vector.
# Example: .{"/usr/bin/git", "commit", "-m", "std.cli"}
#
# Program: the name of the program.
# Example: "/usr/bin/git"
#
# Arg: the user provided elements of the argument vector.
# Example: .{"commit", "-m", "std.cli"}
# There may be zero or more Arg.
#
# EOI: ("end of input") is the end of the os-provided argument vector.
ArgV <- Program Arg* EOI

# Example: "/usr/bin/git"
Program <- STRING

# Example: .{"commit", "-m", "std.cli"}
# Encountering the EndOfOptions symbol ("--") causes all remaining
# Arg to be considered Positional (zero or more).
Arg
    <- EndOfOptions Positional*
    / Optional
    / Positional

# The EndOfOptions symbol is DASHDASH.
# Example: "--"
EndOfOptions <- DASHDASH

# A single DASH ("-") is a valid positional argument, typically representing stdout.
Positional
    <- DASH
    / STRING

# An Option is either a LongOption or a ShortCluster.
Option 
    <- LongOption
    / ShortCluster

# A LongOption begins with "--" and might have a LongArg attached.
# Example: .{"--message", "std.cli"}
# Example: .{"--message=std.cli"}
# Example: .{"--amend"}
LongOption
    <- DASHDASH Name LongArg?

# OptionValue can be attached to LongArg with "=" or detached.
#
# EQUAL is "=".
#
# The following examples come from full command-line:
# .{"git", "commit", "--message=std.cli", "--message", "std.cli"}
#
# Example: "=std.cli"
# Example: "std.cli"
LongArg
    <- EQUAL OptionValue
    / OptionValue

# OptionValue is just a string that gets reinterpreted as some type
# like f32 or i64 by the developer.
OptionValue <- STRING


# A short-cluster is a group of single-character aliases for long options.
# The following examples come from full command-line:
# .{"tar", "-xvf", "zig-x86_64-linux-0.15.2.tar.xz"}
# Example: "-xvf"
# In the above example:
#
# - "x" is a ShortNoArg
# - "v" is a ShortNoArg
# - "f" with "zig-x86_64-linux-0.15.2.tar.xz" is a ShortWithArg.
# 
# A ShortCluster begins with a DASH ("-") and may contain multiple
# ShortNoArg. If there is a ShortWithArg, it must be last.
# The ShortCluster must have at least one short in it.
ShortCluster
    <- DASH ShortNoArg* ShortWithArg
     / DASH ShortNoArg+

# ShortWithArg is "f" and "zig-x86_64-linux-0.15.2.tar.xz" in the following 
# full command-line example (ZON):
# .{"tar", "-xvf", "zig-x86_64-linux-0.15.2.tar.xz"}
ShortWithArg <- ShortFlag ShortArg

# ShortFlag is any ASCII single character.
# The following examples come from full command-line:
# .{"git", "commit", "-m", "std.cli"}
#
# Example: "m"
ShortFlag <- ASCIICHAR

# ShortArg is the argument for a ShortWithArg.
# The following examples come from full command-line:
# .{"git", "commit", "-m", "std.cli"}
#
# Example: "std.cli"
ShortArg <- OptionValue

# Common functionality intentionally omitted:
#
# ShortArg appended to ShortFlag.
# Rejected Example (ZON): .{"-ofile.txt"}
# Accepted Example (ZON): .{"-o", "file.txt"}
# Rationale: Difficult to disambiguate with short-cluster.
