# Zig std.cli Command-line Argument Parser Grammar Specification
# Version: 0.1.0

# To prevent breaking changes experienced by users of applications
# that include std.cli functionality, std.cli MUST conform to
# this specification.

# The style of this document MUST align with the zig language grammar document:
# https://codeberg.org/ziglang/zig-spec/src/branch/master/grammar/grammar.peg
#
# This document describes Parsing Expression Grammar.
# https://en.wikipedia.org/wiki/Parsing_expression_grammar

# The command-line argument parser MAY conform to parts of the following
# specifications:
# - POSIX Utility Conventions: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
# - GNU Program Argument Syntax Conventions: https://sourceware.org/glibc/manual/latest/html_node/Argument-Syntax.html
#
#
# Summary:
# - Aligns with GNU getopt_long, which allows mixing the order of options and positionals.
# - Supports short-clusters, like in `tar -xvf files.tar.gz`.
# - Does not support ShortArg append to ShortFlag, like .{"-o", "file.txt"} in .{"curl", "-ofile.txt", "http://example.com"}
#
# Examples are given in ZON (Zig Object Notation) format.


# ArgV is the POSIX operating-system-provided argument vector.
# The parser is given ArgV.
# Example: .{"/usr/bin/git", "commit", "-m", "std.cli"}
#
# The divisions between the elements are semantically important
# and are denoted as NE ("new element").
#
# SOI ("start of input") is the start of the os-provided argument vector.
# Program is the program name.
# Arg is an argument given to the program, there may be zero or more Arg.
# EOI ("end of input") is the end of the os-provided argument vector.
ArgV <- SOI Program (NE Arg)* EOI

# The program name can be any string.
# Example: "/usr/bin/git"
Program <- STRING

# An Arg may be explicitly beginning positionals, an optional,
# a subcommand, or a positional in that priority order.
#
# Example: Subcommand "commit" in .{"git", "commit", "-m", "std.cli"}
# Example: Option .{"-m", "std.cli"} in .{"git", "commit", "-m", "std.cli"}
# 
# Encountering the EndOfOptions symbol ("--") causes all remaining
# Arg to be considered Positional (zero or more).
#
# Example: .{"--", "README.md", "build.zig.zon"} in .{"git", "add", "--", "README.md", "build.zig.zon"}
# 
# Note that Positional is the lowest priority, so if the user wants to specify a 
# positional that collides with EndOfOptions, Option, Subcommand, they need to use EndOfOptions first.
#
# Example: .{"git", "add", "--", "--verbose"} will add a file named "--verbose".
Arg
    <- EndOfOptions (NE Positional)*
    / Option
    / Subcommand
    / Positional

# The EndOfOptions symbol is DASHDASH.
# Example: "--" in .{"git", "add", "--", "README.md"}
EndOfOptions <- DASHDASH

# Subcommands just begin the argparsing again.
# Arg after subcommand only apply to that subcommand and to not apply to the parents.
#
# Example: .{"commit", "-m", "std.cli"} in .{"git", "commit", "-m", "std.cli"}
Subcommand <- SubcommandName (NE Arg)*

# SubcommandName is only one of the program-author-allowed subcommands.
# 
# Example: "commit" in .{"git" , "commit" , "-m", "std.cli"}
#
# And SUBCOMMANDLIST would be something like .{"commit", "pull", "push", "clone"} etc.
# Note: Subcommand may not start with dash, conflicts with Option.
SubcommandName <- SUBCOMMANDLIST

# A single DASH ("-") is a valid Positional, typically representing stdout.
Positional
    <- DASH
    / STRING

# An Option is either a LongOption or a ShortCluster.
Option 
    <- LongOption
    / ShortCluster

# A LongOption begins with "--" and might have a LongArg attached.
# EQUAL is "=".
#
# Example: .{"--message", "std.cli"} in .{"git" , "commit" , "--message", "std.cli"}
# Example: .{"--message=std.cli"} in .{"git" , "commit" , "--message=std.cli"}
# Example: "--amend" in .{"git" , "commit" , "--amend"}
# Example: .{"--message", ""} in .{"git" , "commit" , "--message="}
LongOption
    <- DASHDASH Name (NE OptionValue)?
    \ DASHDASH Name EQUAL OptionValue

# Name is one of the program-author-allowed long option names for the command.
# 
# Example: "amend" in .{"git" , "commit" , "--amend"}
Name <- LONGOPTIONLIST

# OptionValue is just a string that gets reinterpreted as some type
# like f32 or i64 by the program author.
OptionValue <- STRING


# A short-cluster is a group of single-character aliases for long options.
# The following examples come from full command-line:
#
# Example:"x" is a ShortNoArg in .{"tar", "-xvf", "files.tar.gz"}
# Example: "v" is a ShortNoArg in .{"tar", "-xvf", "files.tar.gz"}
# Example: .{"f", "files.tar.gz"} is a ShortWithArg in .{"tar", "-xvf", "files.tar.gz"}
#
# A ShortCluster begins with a DASH ("-") and may contain multiple
# ShortNoArg. If there is a ShortWithArg, it must be last.
# The ShortCluster must have at least one short in it.
ShortCluster
    <- DASH ShortNoArg* ShortWithArg
     / DASH ShortNoArg+

# Example: .{"f", "files.tar.gz"} in .{"tar", "-xvf", "files.tar.gz"}
ShortWithArg <- ShortFlag NE ShortArg

# ShortFlag is any non-dash single ASCII character.
# Example: "m" in .{"git", "commit", "-m", "std.cli"}
ShortFlag <- ASCIICHARNODASH

# ShortArg is the argument for a ShortWithArg.
# Example: "std.cli" in .{"git", "commit", "-m", "std.cli"}
ShortArg <- OptionValue

# ShortArg appended to ShortFlag is not supported because
# it is too difficult to disambiguate with a short-cluster.
# Rejected example: .{"-ofile.txt"} in .{"curl", "-ofile.txt", "http://example.com"}
# Accepted example: .{"-o", "file.txt"} in .{"curl", "-o", "file.txt", "http://example.com"}
