name: ci

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

# This cancels older workflow runs on pull requests while ensuring that there
# are no concurrency limits on pushes and manual workflow dispatches.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  riscv64-linux-debug:
    runs-on: [self-hosted, riscv64-linux]
    steps:
      - name: Checkout
        uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28
        with:
          fetch-depth: 0
      - name: Build and Test
        run: sh ci/riscv64-linux-debug.sh
        timeout-minutes: 720
  riscv64-linux-release:
    runs-on: [self-hosted, riscv64-linux]
    steps:
      - name: Checkout
        uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28
        with:
          fetch-depth: 0
      - name: Build and Test
        run: sh ci/riscv64-linux-release.sh
        timeout-minutes: 600
