const std = @import("std");
const Io = std.Io;
const process = std.process;

pub fn main(init: process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);

    if (args.len != 3) return error.BadUsage;
    const actual_path = args[1];
    const expected_path = args[2];

    const actual = try Io.Dir.cwd().readFileAlloc(
        io,
        actual_path,
        arena,
        .limited(1024 * 1024),
    );

    const expected = try Io.Dir.cwd().readFileAlloc(
        io,
        expected_path,
        arena,
        .limited(1024 * 1024),
    );

    const comment_str = "/* This file was generated by ConfigHeader using the Zig Build System. */\n";
    if (!std.mem.startsWith(u8, actual, comment_str))
        return error.MissingOrMalformedComment;

    const actual_without_comment = actual[comment_str.len..];

    if (!std.mem.eql(u8, actual_without_comment, expected))
        return error.DoesNotMatch;
}
