/* This file was generated by ConfigHeader using the Zig Build System. */
#ifndef STUB_HEADER_H
#define STUB_HEADER_H
/* #undef FOO1 */
#define FOO2
#define FOO3 1
#define FOO4 0
#define FOO5 42
#define FOO7 -7
#define FOO8 a verbatim/identical example value
#define FOO9 "here's a string for ya"
#endif /* STUB_HEADER_H */
